# Generated by Django 5.0.2 on 2024-03-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
