# Generated by Django 5.0.2 on 2024-03-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delete_status',
        ),
    ]
